version: '3.0'
services:
  storage-contract-node:
    image: 'crustio/storage-contract-node:0.0.1'
    network_mode: 'host'
    volumes:
      - /opt/crust/pinning-node:/opt/crust/pinning-node
    logging:
      driver: json-file
      options:
        max-size: 1000m
    restart: always
    container_name: storage-contract-node
