version: '3.0'
services:
  storage-contract-node:
    image: 'crustio/storage-contract-node:0.0.1'
    ports:
      - "33333:33333"
    logging:
      driver: json-file
      options:
        max-size: 1000m
    restart: always
    container_name: storage-contract-node
